name: Go Test and Linting
on: [pull_request, workflow_dispatch]
jobs:
  lint:
    name: Run Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Linting
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
  test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Fetch dependencies
        run: |
          cd ./api
          go get .
          cd ../racing
          go get .
      - name: Run tests
        run: |
          cd ./api
          go test ./...
          cd ../racing
          go test ./...